version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  server:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server:/app
    links:
      - mongo
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app